# config/packages/sonata_user.yaml

sonata_user:
    class:
        user: App\Entity\User
    resetting:
        email:
            address: admin@web-system.local
            sender_name: Sonata Admin